import photosData from "@/data/photos.json";

export interface Photo {
  src: string;
  width: number;
  height: number;
  year: number | null;
  caption?: string;
}

/**
 * Generated by scripts/prepare-photos.mjs from assets/photos-source/ — see
 * that script for how src/width/height/year are produced. `caption` is the
 * one field the script won't overwrite on a re-run: add captions straight
 * into data/photos.json and they'll survive the next `npm run photos`.
 */
export const PHOTOS: Photo[] = photosData as Photo[];
