import dynastyData from "@/data/dynasty.json";
import redraftData from "@/data/redraft.json";
import type { LeagueType } from "@/config/leagues";
import type { LeagueSnapshot, ManagerTrend, SnapshotSeason } from "@/lib/sleeper/snapshot-types";

/**
 * `data/*.json` is generated by `scripts/snapshot.ts` (wired as a `prebuild`
 * step — see package.json) and imported here directly rather than read from
 * disk at request time, so it gets bundled at build time like any other
 * static import. TypeScript widens JSON-imported string fields to plain
 * `string` (it has no way to know `status` is really one of four literals),
 * so the cast below is bridging "the JSON module type" to "the type we know
 * this data actually satisfies," not asserting something unverified.
 */
const SNAPSHOTS: Record<LeagueType, LeagueSnapshot> = {
  dynasty: dynastyData as LeagueSnapshot,
  redraft: redraftData as LeagueSnapshot,
};

export function getLeagueSnapshot(league: LeagueType): LeagueSnapshot {
  return SNAPSHOTS[league];
}

export function getCompletedSeasons(snapshot: LeagueSnapshot): SnapshotSeason[] {
  return snapshot.seasons.filter((s) => s.status === "complete");
}

/**
 * The season standings pages should lead with: the in-progress season if
 * one's being played, else the most recently completed one, else whatever's
 * there (a brand-new league with only a pre-draft season) so this never
 * has nothing to return.
 */
export function getCurrentSeason(snapshot: LeagueSnapshot): SnapshotSeason {
  const inSeason = snapshot.seasons.find((s) => s.status === "in_season");
  if (inSeason) return inSeason;

  const completed = getCompletedSeasons(snapshot);
  if (completed.length > 0) return completed[completed.length - 1];

  return snapshot.seasons[snapshot.seasons.length - 1];
}

export function computeManagerTrends(snapshot: LeagueSnapshot): ManagerTrend[] {
  const completed = getCompletedSeasons(snapshot);

  interface Accum {
    teamName: string;
    displayName: string;
    avatar: string | null;
    seasonsPlayed: number;
    wins: number;
    losses: number;
    ties: number;
    finishes: number[];
  }

  const byOwner = new Map<string, Accum>();

  for (const season of completed) {
    for (const team of season.teams) {
      if (!team.ownerId) continue;

      const entry = byOwner.get(team.ownerId) ?? {
        teamName: team.teamName,
        displayName: team.displayName,
        avatar: team.avatar,
        seasonsPlayed: 0,
        wins: 0,
        losses: 0,
        ties: 0,
        finishes: [],
      };

      // Seasons are iterated oldest -> newest, so overwriting these each
      // time leaves the manager's *current* team name/avatar in the trend,
      // even though older seasons may have used a different one.
      entry.teamName = team.teamName;
      entry.displayName = team.displayName;
      entry.avatar = team.avatar;
      entry.seasonsPlayed += 1;
      entry.wins += team.wins;
      entry.losses += team.losses;
      entry.ties += team.ties;
      if (team.finish != null) entry.finishes.push(team.finish);

      byOwner.set(team.ownerId, entry);
    }
  }

  return Array.from(byOwner.entries())
    .map(([ownerId, e]): ManagerTrend => ({
      ownerId,
      teamName: e.teamName,
      displayName: e.displayName,
      avatar: e.avatar,
      seasonsPlayed: e.seasonsPlayed,
      wins: e.wins,
      losses: e.losses,
      ties: e.ties,
      avgFinish: e.finishes.length > 0 ? e.finishes.reduce((a, b) => a + b, 0) / e.finishes.length : null,
      bestFinish: e.finishes.length > 0 ? Math.min(...e.finishes) : null,
      worstFinish: e.finishes.length > 0 ? Math.max(...e.finishes) : null,
    }))
    .sort((a, b) => b.wins - a.wins);
}
